
# Site settings
title: Photography by Bal치zs Orb치n
email: info@balazsorban.com
description: Here you will find my best pictures taken so far.
baseurl: "/photo" # the subpath of your site, e.g. /blog
url: "http://balazsorban.com" # the base hostname & protocol for your site
#url: "http://192.168.1.4:8000" # the base hostname & protocol for your site
homepage: "http://balazsorban.com"
author: Bal치zs Orb치n
# Build settings
markdown: kramdown
destination: ../photo
