# Site settings
url: http://balazsorban.com # the base hostname & protocol for your site
#url: http://127.0.0.1:8000 # the base hostname & protocol for your site
title: Photography by Bal치zs Orb치n
email: info@balazsorban.com
description: Here you will find my best pictures taken so far.
baseurl: /photo # the subpath of your site, e.g. /blog
localpath: /home/balazs/Documents/github/balazsorban44.github.io
homepage: http://balazsorban.com
author: Bal치zs Orb치n
# Build settings
markdown: kramdown
destination: ../photo
