gem 'jekyll-admin', group: :jekyll_plugins
source: ../../src/jekyll/
destination: ../../docs/
keep_files: [assets/img, assets/css, index.html, assets/js, photo/img, code/img]
exclude: [Gemfile, Gemfile.lock]
homepage: http://0.0.0.0:4000
author: Balázs Orbán
email: info@balazsorban.com
phone: +4795460627
# Build settings
markdown: kramdown
